# Multiple Linear Regression

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
from google.colab import files
uploaded = files.upload()
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Saving 50_Startups.csv to 50_Startups (2).csv


In [ ]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

## Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


## Building the optimal model using Backward Elimination

In [ ]:
import statsmodels.api as sm

In [ ]:
X = dataset.iloc[:,:-1]
X = pd.get_dummies(X, columns=['State'])
X_opt = X.iloc[:,:-1]
print(X_opt)

    R&D Spend  Administration  Marketing Spend  State_California  \
0   165349.20       136897.80        471784.10                 0   
1   162597.70       151377.59        443898.53                 1   
2   153441.51       101145.55        407934.54                 0   
3   144372.41       118671.85        383199.62                 0   
4   142107.34        91391.77        366168.42                 0   
5   131876.90        99814.71        362861.36                 0   
6   134615.46       147198.87        127716.82                 1   
7   130298.13       145530.06        323876.68                 0   
8   120542.52       148718.95        311613.29                 0   
9   123334.88       108679.17        304981.62                 1   
10  101913.08       110594.11        229160.95                 0   
11  100671.96        91790.61        249744.55                 1   
12   93863.75       127320.38        249839.44                 0   
13   91992.39       135495.07        252664.93  

In [ ]:
y = dataset.iloc[:,-1]
print(y)

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64


In [1]:
X_opt = sm.add_constant(X_opt)
print(X_opt)

NameError: name 'sm' is not defined

In [ ]:
regressor_OLS = sm.OLS(y, X_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sat, 09 Mar 2024   Prob (F-statistic):           1.34e-27
Time:                        08:33:37   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const             5.008e+04   6952.587  

In [2]:
X_opt = X_opt.iloc[:,[0,1,2,3,5]]
print(X_opt)

NameError: name 'X_opt' is not defined

In [ ]:
regressor_OLS = sm.OLS(y, X_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Sat, 09 Mar 2024   Prob (F-statistic):           8.49e-29
Time:                        08:38:40   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            5.011e+04   6647.870     

In [ ]:
X_opt = X_opt.iloc[:,[0,1,2,3]]
print(X_opt)

    const  R&D Spend  Administration  Marketing Spend
0     1.0  165349.20       136897.80        471784.10
1     1.0  162597.70       151377.59        443898.53
2     1.0  153441.51       101145.55        407934.54
3     1.0  144372.41       118671.85        383199.62
4     1.0  142107.34        91391.77        366168.42
5     1.0  131876.90        99814.71        362861.36
6     1.0  134615.46       147198.87        127716.82
7     1.0  130298.13       145530.06        323876.68
8     1.0  120542.52       148718.95        311613.29
9     1.0  123334.88       108679.17        304981.62
10    1.0  101913.08       110594.11        229160.95
11    1.0  100671.96        91790.61        249744.55
12    1.0   93863.75       127320.38        249839.44
13    1.0   91992.39       135495.07        252664.93
14    1.0  119943.24       156547.42        256512.92
15    1.0  114523.61       122616.84        261776.23
16    1.0   78013.11       121597.55        264346.06
17    1.0   94657.16       1

In [ ]:
regressor_OLS = sm.OLS(y, X_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Sat, 09 Mar 2024   Prob (F-statistic):           4.53e-30
Time:                        08:39:22   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            5.012e+04   6572.353     

In [ ]:
X_opt = X_opt.iloc[:,[0,1,3]]
print(X_opt)

    const  R&D Spend  Marketing Spend
0     1.0  165349.20        471784.10
1     1.0  162597.70        443898.53
2     1.0  153441.51        407934.54
3     1.0  144372.41        383199.62
4     1.0  142107.34        366168.42
5     1.0  131876.90        362861.36
6     1.0  134615.46        127716.82
7     1.0  130298.13        323876.68
8     1.0  120542.52        311613.29
9     1.0  123334.88        304981.62
10    1.0  101913.08        229160.95
11    1.0  100671.96        249744.55
12    1.0   93863.75        249839.44
13    1.0   91992.39        252664.93
14    1.0  119943.24        256512.92
15    1.0  114523.61        261776.23
16    1.0   78013.11        264346.06
17    1.0   94657.16        282574.31
18    1.0   91749.16        294919.57
19    1.0   86419.70             0.00
20    1.0   76253.86        298664.47
21    1.0   78389.47        299737.29
22    1.0   73994.56        303319.26
23    1.0   67532.53        304768.73
24    1.0   77044.01        140574.81
25    1.0   

In [ ]:
regressor_OLS = sm.OLS(y, X_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                 Profit   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Sat, 09 Mar 2024   Prob (F-statistic):           2.16e-31
Time:                        08:39:57   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            4.698e+04   2689.933     